version: '2'

services:
  pd1:
    image: pingcap/pd:pre-ga
    expose:
      - "2379"
      - "2380"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/pd1:/var/data/pd1
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd1:2379
      - --advertise-peer-urls=http://pd1:2380
      - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380
      - --data-dir=/var/data/pd1
    privileged: true

  pd2:
    image: pingcap/pd:pre-ga
    expose:
      - "2379"
      - "2380"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/pd2:/var/data/pd2

    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd2:2379
      - --advertise-peer-urls=http://pd2:2380
      - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380
      - --data-dir=/var/data/pd2
    privileged: true

  pd3:
    image: pingcap/pd:pre-ga
    expose:
      - "2379"
      - "2380"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/pd3:/var/data/pd3

    command:
      - --name=pd3
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd3:2379
      - --advertise-peer-urls=http://pd3:2380
      - --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380
      - --data-dir=/var/data/pd3

    privileged: true

  tikv1:
    image: pingcap/tikv:pre-ga
    expose:
      - "20160"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/tikv1:/var/tikv1
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --data-dir=/var/tikv1
      - --pd=pd1:2379,pd2:2379,pd3:2379

    depends_on:
      - "pd1"
      - "pd2"
      - "pd3"

    entrypoint: /tikv-server

    privileged: true

  tikv2:
    image: pingcap/tikv:pre-ga
    expose:
      - "20160"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/tikv2:/var/tikv2

    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv2:20160
      - --data-dir=/var/tikv2
      - --pd=pd1:2379,pd2:2379,pd3:2379

    depends_on:
      - "pd1"
      - "pd2"
      - "pd3"

    entrypoint: /tikv-server

    privileged: true

  tikv3:
    image: pingcap/tikv:pre-ga
    expose:
      - "20160"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/tikv3:/var/tikv3

    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv3:20160
      - --data-dir=/var/tikv3
      - --pd=pd1:2379,pd2:2379,pd3:2379

    depends_on:
      - "pd1"
      - "pd2"
      - "pd3"

    entrypoint: /tikv-server

    privileged: true

  tidb:
    image: pingcap/tidb:pre-ga
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - /etc/localtime:/etc/localtime:ro

    command:
      - --store=tikv
      - --path=pd1:2379,pd2:2379,pd3:2379
      - -L=info

    depends_on:
      - "tikv1"
      - "tikv2"
      - "tikv3"

    privileged: true
