version: "3"
networks:
  scylla_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
services:
  scylla1:
    image: scylladb/scylla:latest
    networks:
      scylla_net:
        ipv4_address: 172.16.238.10
    volumes:
      - ./data/scylla1:/var/lib/scylla
    command:
      - --smp
      - "1"
      - --seeds
      - 172.16.238.10,172.16.238.11,172.16.238.12
      # - --memory
      # - 2G
      - --developer-mode
      - "1"
  scylla2:
    image: scylladb/scylla:latest
    networks:
      scylla_net:
        ipv4_address: 172.16.238.11
    volumes:
      - ./data/scylla2:/var/lib/scylla
    command:
      - --smp
      - "1"
      - --seeds
      - 172.16.238.10,172.16.238.11,172.16.238.12
      # - --memory
      # - 2G
      - --developer-mode
      - "1"
  scylla3:
    image: scylladb/scylla:latest
    networks:
      scylla_net:
        ipv4_address: 172.16.238.12
    volumes:
      - ./data/scylla3:/var/lib/scylla
    command:
      - --smp
      - "1"
      - --seeds
      - 172.16.238.10,172.16.238.11,172.16.238.12
      # - --memory
      # - 1G
      - --developer-mode
      - "1"


