version: '2'
services:
  telegraf:
    image: telegraf:1.3.5-alpine
    restart: always
    ports:
      - 8094:8094
      - 8092:8092
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

